name: fgc-02

volumes:
  sqlserver-data:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: fgc-sqlserver
    hostname: sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "rohPav-juKmeb-DIhku9!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P rohPav-juKmeb-DIhku9! -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
  rabbitmq:
    image: rabbitmq:management
    container_name: fgc-rabbitmq
    hostname: fgc-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
  user-service:
    image: fgc-user-service:latest
    build:
      context: ../user-service
      dockerfile: Dockerfile
    container_name: fgc-user-service
    hostname: user-service
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Release
      ConnectionStrings__Default: "Server=sqlserver;Database=UsersDb;User Id=sa;Password=rohPav-juKmeb-DIhku9!;TrustServerCertificate=True"
      Jwt__Issuer: fgcapi
      Jwt__Audience: fgcapi
      Jwt__Key: 8594df0eb5ecb4c96f8824462cc7d2e1885c138908f2f7b4357af54b72ab2ed6
      Jwt__TokenTtlInMinutes: 10
      RootUser__FirstName: FirstName
      RootUser__LastName: LastName
      RootUser__Email: admin@fgc.com
      RootUser__Password: Admin@123
      RabbitMQ__URI: amqp://admin:admin123@fgc-rabbitmq:5672/
      RabbitMQ__UserCreatedEvent__Exchange: fgc
      RabbitMQ__UserCreatedEvent__RoutingKey: user.created
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  notification-service:
    image: fgc-notification-service:latest
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    container_name: fgc-notification-service
    hostname: notification-service
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Release      
      RabbitMQ__URI: amqp://admin:admin123@fgc-rabbitmq:5672/
      RabbitMQ__UserCreatedEvent__Exchange: fgc
      RabbitMQ__UserCreatedEvent__RoutingKey: user.created
    depends_on:
      rabbitmq:
        condition: service_healthy
  
